In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"synthetic_online_retail_data.csv")
df.head(10)

,customer_id,order_date,product_id,category_id,category_name,product_name,quantity,price,payment_method,city,review_score,gender,age
0,13542,2024-12-17,784,10,Electronics,Smartphone,2,373.36,Credit Card,New Oliviaberg,1.0,F,56
1,23188,2024-06-01,682,50,Sports & Outdoors,Soccer Ball,5,299.34,Credit Card,Port Matthew,NaN,M,59
2,55098,2025-02-04,684,50,Sports & Outdoors,Tent,5,23.00,Credit Card,West Sarah,5.0,F,64
3,65208,2024-10-28,204,40,Books & Stationery,Story Book,2,230.11,Bank Transfer,Hernandezburgh,5.0,M,34
4,63872,2024-05-10,202,20,Fashion,Skirt,4,176.72,Credit Card,Jenkinshaven,1.0,F,33
5,29989,2024-12-03,829,10,Electronics,Smartphone,4,196.16,Bank Transfer,East Tonyaberg,5.0,F,21
6,79809,2024-06-07,706,10,Electronics,Tablet,5,272.75,Bank Transfer,North Jessicabury,NaN,M,57
7,27282,2024-07-15,405,50,Sports & Outdoors,Yoga Mat,2,292.90,Cash on Delivery,Aliciaberg,NaN,F,60
8,41394,2024-12-17,549,30,Home & Living,Pillow,3,429.11,Credit Card,West Larrymouth,3.0,F,69
9,48695,2024-04-12,545,30,Home & Living,Blanket,4,191.39,Credit Card,Lake Ian,5.0,F,34

In [4]:
df.isna().sum()

customer_id         0
order_date          0
product_id          0
category_id         0
category_name       0
product_name        0
quantity            0
price               0
payment_method      0
city                0
review_score      201
gender            103
age                 0
dtype: int64

In [5]:
df['review_score'].fillna(df['review_score'].mean(), inplace=True)

C:\Users\luqma\AppData\Local\Temp\ipykernel_26688\516660258.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['review_score'].fillna(df['review_score'].mean(), inplace=True)

0      1.000000
1      3.992491
2      5.000000
3      5.000000
4      1.000000
         ...
995    3.992491
996    3.000000
997    3.992491
998    3.000000
999    1.000000
Name: review_score, Length: 1000, dtype: float64

In [6]:
df['order_id'] = range(len(df))

customers_df → customer_id, gender, age, city 

products_df → product_id, product_name, category_name, price 

orders_df → order_id, customer_id, product_id, order_date, quantity, payment_method, review_score

In [25]:
customers_df = df[['customer_id', 'gender', 'age', 'city']].drop_duplicates().reset_index(drop=True)
products_df = df[['product_id', 'product_name', 'category_name', 'price']].drop_duplicates().reset_index(drop=True)
orders_df = df[['order_id', 'customer_id', 'product_id', 'order_date', 'quantity', 'payment_method', 'review_score']].copy()

In [26]:
products_df.head(10)

   product_id product_name       category_name   price
0           0   Smartphone         Electronics  373.36
1           1  Soccer Ball   Sports & Outdoors  299.34
2           2         Tent   Sports & Outdoors   23.00
3           3   Story Book  Books & Stationery  230.11
4           4        Skirt             Fashion  176.72
5           0   Smartphone         Electronics  196.16
6           5       Tablet         Electronics  272.75
7           6     Yoga Mat   Sports & Outdoors  292.90
8           7       Pillow       Home & Living  429.11
9           8      Blanket       Home & Living  191.39

In [27]:
customers_df.head(5)

   customer_id gender  age            city
0        13542      F   56  New Oliviaberg
1        23188      M   59    Port Matthew
2        55098      F   64      West Sarah
3        65208      M   34  Hernandezburgh
4        63872      F   33    Jenkinshaven

In [28]:
orders_df.head(10)

,order_id,customer_id,product_id,order_date,quantity,payment_method,review_score
0,0,13542,0,2024-12-17,2,Credit Card,1.0
1,1,23188,1,2024-06-01,5,Credit Card,NaN
2,2,55098,2,2025-02-04,5,Credit Card,5.0
3,3,65208,3,2024-10-28,2,Bank Transfer,5.0
4,4,63872,4,2024-05-10,4,Credit Card,1.0
5,5,29989,0,2024-12-03,4,Bank Transfer,5.0
6,6,79809,5,2024-06-07,5,Bank Transfer,NaN
7,7,27282,6,2024-07-15,2,Cash on Delivery,NaN
8,8,41394,7,2024-12-17,3,Credit Card,3.0
9,9,48695,8,2024-04-12,4,Credit Card,5.0

Remove duplicates in customer_df and products df

In [30]:
# remove duplicates by id and reset index
products_before = len(products_df)
products_df.drop_duplicates(subset=['product_name'], keep='first', inplace=True)
products_df.reset_index(drop=True, inplace=True)

customers_before = len(customers_df)
customers_df.drop_duplicates(subset=['customer_id'], keep='first', inplace=True)
customers_df.reset_index(drop=True, inplace=True)

print(f"products: {products_before} -> {len(products_df)}; customers: {customers_before} -> {len(customers_df)}")

products: 25 -> 25; customers: 1000 -> 1000

In [31]:
df['product_name'].value_counts()

product_name
Yoga Mat         51
Eraser           48
Smartphone       47
Pants            46
Soccer Ball      45
Headphones       45
Notebook         44
Running Shoes    42
Skirt            41
Laptop           40
T-shirt          40
Tablet           39
Blanket          39
Vase             39
Painting         39
Dress            38
Tent             37
Pillow           37
Carpet           37
Smartwatch       36
Pen              36
Basketball       36
Story Book       33
Shirt            33
Novel            32
Name: count, dtype: int64

Final tables...

In [34]:
print("customers_df")
print(customers_df.head(5))

print("\nproducts_df")
print(products_df.head(5))

print("\norders_df")
print(orders_df.head(5))

customers_df
   customer_id gender  age            city
0        13542      F   56  New Oliviaberg
1        23188      M   59    Port Matthew
2        55098      F   64      West Sarah
3        65208      M   34  Hernandezburgh
4        63872      F   33    Jenkinshaven

products_df
   product_id product_name       category_name   price
0           0   Smartphone         Electronics  373.36
1           1  Soccer Ball   Sports & Outdoors  299.34
2           2         Tent   Sports & Outdoors   23.00
3           3   Story Book  Books & Stationery  230.11
4           4        Skirt             Fashion  176.72

orders_df
   order_id  customer_id  product_id  order_date  quantity payment_method  \
0         0        13542           0  2024-12-17         2    Credit Card
1         1        23188           1  2024-06-01         5    Credit Card
2         2        55098           2  2025-02-04         5    Credit Card
3         3        65208           3  2024-10-28         2  Bank Transfer
4         4        63872           4  2024-05-10         4    Credit Card

   review_score
0           1.0
1           NaN
2           5.0
3           5.0
4           1.0

In [33]:
orders_df

,order_id,customer_id,product_id,order_date,quantity,payment_method,review_score
0,0,13542,0,2024-12-17,2,Credit Card,1.0
1,1,23188,1,2024-06-01,5,Credit Card,NaN
2,2,55098,2,2025-02-04,5,Credit Card,5.0
3,3,65208,3,2024-10-28,2,Bank Transfer,5.0
4,4,63872,4,2024-05-10,4,Credit Card,1.0
...,...,...,...,...,...,...,...
995,995,67967,10,2024-05-04,3,Cash on Delivery,NaN
996,996,99828,3,2024-09-12,5,Credit Card,3.0
997,997,92290,0,2024-11-06,5,Bank Transfer,NaN
998,998,61427,11,2024-09-17,4,Cash on Delivery,3.0
999,999,20658,12,2024-11-06,3,Cash on Delivery,1.0

In [43]:
len(products_df), len(customers_df), len(orders_df)

(1000, 1000, 1000)

In [45]:
unique_ids = df['product_id'].dropna().nunique()
unique_names = df['product_name'].dropna().nunique()
print(f"unique product_id: {unique_ids}, unique product_name: {unique_names}")

products_df = (
    df[['product_id', 'product_name', 'category_name', 'price']]
      .drop_duplicates(subset=['product_id'])
      .reset_index(drop=True)
)

print(f"products_df length after dedup: {len(products_df)}")
products_df.head(10)

unique product_id: 25, unique product_name: 25
products_df length after dedup: 25

   product_id product_name       category_name   price
0           0   Smartphone         Electronics  373.36
1           1  Soccer Ball   Sports & Outdoors  299.34
2           2         Tent   Sports & Outdoors   23.00
3           3   Story Book  Books & Stationery  230.11
4           4        Skirt             Fashion  176.72
5           5       Tablet         Electronics  272.75
6           6     Yoga Mat   Sports & Outdoors  292.90
7           7       Pillow       Home & Living  429.11
8           8      Blanket       Home & Living  191.39
9           9   Smartwatch         Electronics  321.14

In [61]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../cleaned_data.db")

customers_df.to_sql("customers", conn, if_exists="replace", index=False)
orders_df.to_sql("orders", conn, if_exists="replace", index=False)
products_df.to_sql("products", conn, if_exists="replace", index=False)

tables = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

print(tables)

print(pd.read_sql("SELECT COUNT(*) AS total_customers FROM customers", conn))
print(pd.read_sql("SELECT COUNT(*) AS total_orders FROM orders", conn))
print(pd.read_sql("SELECT COUNT(*) AS total_products FROM products", conn))

conn.commit()
conn.close()

        name
0  customers
1     orders
2   products
   total_customers
0             1000
   total_orders
0          1000
   total_products
0              25

checking the db.......

In [63]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../cleaned_data.db")

In [64]:
order_id = 999

query = """
SELECT o.order_id,
    o.product_id,
    p.product_name
FROM orders AS o
JOIN products AS p
  ON o.product_id = p.product_id
WHERE o.order_id = ?
"""

product_for_order = pd.read_sql_query(query, conn, params=(order_id,))
product_for_order
conn.close()

In [ ]:
conn = sqlite3.connect("../cleaned_data.db")

query = """
SELECT SUM(o.quantity) AS total_smartphones_sold
FROM orders AS o
JOIN products AS p
    ON o.product_id = p.product_id
WHERE lower(p.category_name) LIKE '%smartphone%'
     OR lower(p.product_name) LIKE '%smartphone%'
"""

result = pd.read_sql_query(query, conn)
print(result)

conn.close()